### ISSUE TITLE
anomaly: "Assert_failure src/expression.ml:599:18"

### ISSUE THREAD

**Issue by fpottier** [ocaml-gospel/cameleer#21]
Opening the following `.ml` file with Cameleer causes this error message to be displayed:
```
anomaly: "Assert_failure src/expression.ml:599:18"
```
The code is as follows:
```
type 'a t = {
  default: 'a;
  mutable table: 'a array;
  (* invariant: the length of the array [table] is nonzero *)
}

let make n x =
  assert (n > 0);
  let default = x
  and table = Array.make n x in
  { default; table }
```
This happens with and without a matching `.mli` file.

**Comment by mariojppereira** [comment]
Thank you for reporting. I guess I was being really lazy and not supporting `let..and` expressions :)

PR#24 should fix this.
