### ISSUE TITLE
Dynlink error: The module `Sexplib0__Raw_grammar' is already loaded

### ISSUE THREAD

**Issue by talex5** [ocaml-gospel/cameleer#7]
After updating to fix #6, I got it installed. But it gives an error when running it on a file:
```
$ echo 'print_endline "Hi"' > test.ml
$ cameleer test.ml
/home/user/.opam/4.12.0/lib/why3/plugins/plugin_cameleer cannot be loaded: 
Dynlink error: The module `Sexplib0__Raw_grammar' is already loaded (either by the main program or a previously-dynlinked library)
```
At the same time, why3 opens a window saying:
```
Session initialized successfully
There was an unrecoverable error during treatment of request:
 open file /home/user/tmp/cam/test.ml
with exception: 
Unknown file extension: `ml'
```

I also tried it on some of the examples. That didn't open the why3 window at all, but reported:
```
$ cameleer duplicates.ml
/home/user/.opam/4.12.0/lib/why3/plugins/plugin_cameleer cannot be loaded: 
Dynlink error: The module `Sexplib0__Raw_grammar' is already loaded (either by the main program or a previously-dynlinked library)
warning: [Warning] could not read goal shapes because Why3 was not compiled with compress support

Unknown file extension: `ml'
```

**Comment by talex5** [comment]
BTW, feel free to enable ocaml-ci on this repository (https://github.com/apps/ocaml-ci).

Note: it's already enabled for some of the others repositories (https://ci.ocamllabs.io/github/ocaml-gospel), but it isn't currently showing the status on the PRs because someone needs to approve its request for access to the GitHub Checks API, which it recently switched to using.

**Comment by mariojppereira** [comment]
> After updating to fix #6, I got it installed. But it gives an error when running it on a file:
> 
> ```
> $ echo 'print_endline "Hi"' > test.ml
> $ cameleer test.ml
> /home/user/.opam/4.12.0/lib/why3/plugins/plugin_cameleer cannot be loaded: 
> Dynlink error: The module `Sexplib0__Raw_grammar' is already loaded (either by the main program or a previously-dynlinked library)
> ```
> 
> At the same time, why3 opens a window saying:
> 
> ```
> Session initialized successfully
> There was an unrecoverable error during treatment of request:
>  open file /home/user/tmp/cam/test.ml
> with exception: 
> Unknown file extension: `ml'
> ```
> 
> I also tried it on some of the examples. That didn't open the why3 window at all, but reported:
> 
> ```
> $ cameleer duplicates.ml
> /home/user/.opam/4.12.0/lib/why3/plugins/plugin_cameleer cannot be loaded: 
> Dynlink error: The module `Sexplib0__Raw_grammar' is already loaded (either by the main program or a previously-dynlinked library)
> warning: [Warning] could not read goal shapes because Why3 was not compiled with compress support
> 
> Unknown file extension: `ml'
> ```

Thank you for reporting. This should now be fixed.

The issue with `Sexplib0__Raw_grammar` is that this is an optional dependency of Why3. Hence, one could install Why3 with or without it, which in the later case would make us change once again the `dune` file of Cameleer.

In the meantime, I think the best compromise is to assume that Why3 was installed with sexplib0 as this is the most common case.

**Comment by mariojppereira** [comment]
> BTW, feel free to enable ocaml-ci on this repository (https://github.com/apps/ocaml-ci).
> 
> Note: it's already enabled for some of the others repositories (https://ci.ocamllabs.io/github/ocaml-gospel), but it isn't currently showing the status on the PRs because someone needs to approve its request for access to the GitHub Checks API, which it recently switched to using.

Thank you for the suggestion. I will certainly do it and also fix it for the other projects of OCaml-GOSPEL.

**Comment by talex5** [comment]
Thanks - I was able to follow your tutorial with the latest version :-)
